In [1]:
import numpy as np
import pandas as pd

In [2]:
file = None
while file is None:
    try:
        
        n = input('Enter a class to grade (i.e. class1 for class1.txt): ')
              
        file = open(f'Data Files/{n}.txt', 'r')
        
        print(f'Successfully opened {n}.txt\n')
        print('**** ANALYZING ****\n')
    except:
        print('File cannot be found.\nPlease try again!')
valid = 0
invalid = 0
valid_line =[]
for i in file:
    line = i.strip().split(',')
    
    if len(line) != 26:
        print('Invalid line of data: does not contain exactly 26 values:')
        print(i, '\n')
        invalid += 1
        
    elif len(line[0]) != 9 or not line[0].startswith('N') or not line[0][1:].isnumeric():
        print('Invalid line of data: N# is invalid')
        print(i, '\n')
        invalid += 1
    else:
        valid += 1
        valid_line.append(line)
        

if invalid == 0:
    print('No errors found!\n')
    
print('**** REPORT ****\n')
print('Total valid lines of data:', valid)
print('Total invalid lines of data:', invalid, '\n')

answer_key = "B,A,D,D,C,B,D,A,C,C,D,B,A,B,A,C,B,D,A,C,A,A,B,D,D".split(',')

result = []

for i in valid_line:
    score = 0
    #stu = i[0]
    for u, v in zip(answer_key, i[1:]):
        
        if u == v:
            score += 4
        elif v == '':
            continue
        else:
            score -= 1
    result.append([i[0] ,score])
    
df = pd.DataFrame(result)
df.to_csv(f'{n}_grades.txt', header = False, index = False)
print('Mean (average) score: {:.2f}'.format(df[1].mean()))
print('Highest score:', df[1].max())
print('Lowest score:', df[1].min())
print('Range of scores:', df[1].max() - df[1].min())
print('Median score:', df[1].median(), '\n')

Enter a class to grade (i.e. class1 for class1.txt): class1
Successfully opened class1.txt

**** ANALYZING ****

No errors found!

**** REPORT ****

Total valid lines of data: 20
Total invalid lines of data: 0

Mean (average) score: 75.60
Highest score: 91
Lowest score: 59
Range of scores: 32
Median score: 73.0

In [2]:
file = None
while file is None:
    try:
        
        n = input('Enter a class to grade (i.e. class1 for class1.txt): ')
              
        file = open(f'Data Files/{n}.txt', 'r')
        
        print(f'Successfully opened {n}.txt\n')
        print('**** ANALYZING ****\n')
    except:
        print('File cannot be found.\nPlease try again!')

invalid = 0
valid_line =[]
for i in file:
    line = i.strip().split(',')
    
    if len(line) != 26:
        print('Invalid line of data: does not contain exactly 26 values:')
        print(i, '\n')
        invalid += 1
        
    elif len(line[0]) != 9 or not line[0].startswith('N') or not line[0][1:].isnumeric():
        print('Invalid line of data: N# is invalid')
        print(i, '\n')
        invalid += 1
    else:
        
        valid_line.append(line)
        

if invalid == 0:
    print('No errors found!\n')
    
print('**** REPORT ****\n')
print('Total valid lines of data:', len(valid_line))
print('Total invalid lines of data:', invalid, '\n')


all_student = pd.DataFrame(valid_line)
all_student.set_index(0, inplace = True)
all_student.index.name = None
all_student.columns = list(range(0,25))

answer_key = pd.Series("B,A,D,D,C,B,D,A,C,C,D,B,A,B,A,C,B,D,A,C,A,A,B,D,D".split(','))
all_student.replace('', 0, inplace = True)
all_student[all_student == answer_key] = 4
all_student[~all_student.isin([0,4])] = -1
all_student = all_student.astype(int)
score = all_student.sum(axis = 1)


score.to_csv(f'{n}_grades.txt', header = False)
print('Mean (average) score: {:.2f}'.format(score.mean()))
print('Highest score:', score.max())
print('Lowest score:', score.min())
print('Range of scores:', score.max() - score.min())
print('Median score:', score.median(), '\n')

Enter a class to grade (i.e. class1 for class1.txt): class1
Successfully opened class1.txt

**** ANALYZING ****

No errors found!

**** REPORT ****

Total valid lines of data: 20
Total invalid lines of data: 0

Mean (average) score: 75.60
Highest score: 91
Lowest score: 59
Range of scores: 32
Median score: 73.0

In [4]:
all_student == answer_key

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
N00000001,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
N00000002,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
N00000003,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
N00000004,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
N00000005,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
N00000006,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
N00000007,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
N00000008,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
N00000009,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
N00000010,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
N00000011,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
N00000012,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
N00000013,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
N00000014,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
N00000015,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
N00000016,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
N00000017,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
N00000018,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
N00000019,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
N00000020,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [21]:
import numpy as np
import pandas as pd

#Load file
file = None
while file is None:
    try:
        n = input('Enter a class to grade (i.e. class1 for class1.txt): ')             
        file = open(f'Data Files/{n}.txt', 'r')       
        print(f'Successfully opened {n}.txt\n')
        print('**** ANALYZING ****\n')
    except:
        print('File cannot be found.\nPlease try again!')

#Check line validity, print out invalid line
invalid = 0
valid_line =[]
for i in file:
    line = i.strip().split(',')
    
    if len(line) != 26:
        print('Invalid line of data: does not contain exactly 26 values:')
        print(i, '\n')
        invalid += 1
        
    elif len(line[0]) != 9 or not line[0].startswith('N') or not line[0][1:].isnumeric():
        print('Invalid line of data: N# is invalid')
        print(i, '\n')
        invalid += 1

    else:      
        valid_line.append(line)
        
#print out report for number of valid and invalid lines
if invalid == 0:
    print('No errors found!\n')   
print('**** REPORT ****\n')
print('Total valid lines of data:', len(valid_line))
print('Total invalid lines of data:', invalid, '\n')

#create a Data Frame to store valid students scores
all_student = pd.DataFrame(valid_line)
all_student.set_index(0, inplace = True)
all_student.index.name = None
all_student.columns = list(range(0,25))

answer_key = pd.Series("D,C,B,D,A,C,C,D,B,A,B,A,C,B,D,A,C,A,A,B,D,D".split(','))

Enter a class to grade (i.e. class1 for class1.txt): class2
Successfully opened class2.txt

**** ANALYZING ****

Invalid line of data: does not contain exactly 26 values:
N00000023,,A,D,D,C,B,D,A,C,C,,C,,B,A,C,B,D,A,C,A,A


Invalid line of data: N# is invalid
N0000002,B,A,D,D,C,B,D,A,C,D,D,D,A,,A,C,D,,A,C,A,A,B,D,D


Invalid line of data: N# is invalid
NA0000027,B,A,D,D,,B,,A,C,B,D,B,A,,A,C,B,D,A,,A,A,B,D,D


Invalid line of data: does not contain exactly 26 values:
N00000035,B,A,D,D,B,B,,A,C,,D,B,A,B,A,A,B,D,A,C,A,C,B,D,D,A,A


**** REPORT ****

Total valid lines of data: 21
Total invalid lines of data: 4

In [19]:
all_student

          0  1  2  3  4  5  6  7  8  9   ... 15 16 17 18 19 20 21 22 23 24
N00000001  A  A  D  D  C  D  D  A     C  ...  C  B  D  A  C     A     C  D
N00000002     A     D     B  D  A  C  C  ...  C  B  D  C  C  A  A  B     D
N00000003  B  A     D  C  B  D  A  C  C  ...  C  B  D  A     A     B  D  D
N00000004  B  B  D        B  D  A  C  C  ...  C  B  D     C  A  D  B  C  D
N00000005  B  A     D     B  D  A  C  C  ...  C  B  D  D  C  A  A     D  D
N00000006  B  A  D  A  C  B  D  A  C  C  ...  C     C  A  C  A  C  B  D  A
N00000007  B  A  D  D  C  B  D  A  C     ...  C  B  D     C  A  A  B  D
N00000008  A  A  D  D  C     D  A  C  C  ...  A  B  D  A  C  A     B  B  D
N00000009  B  A     D  C  B  D  A  C  A  ...  A  B  D  A  C  A  A  B  D  D
N00000010     A  D  B  C  B  D  A  C  C  ...  C  B  D  A  D        B  D  B
N00000011  B  A  D     C  B  D  A  C  D  ...  C  B  D  A  C  A  B  B  D  D
N00000012  B     D  D  C  B  D  A  C  C  ...  A  B  D  A     A  A  A     C
N00000013     A  D     B  B     A  C  A  ...  C  B  D  A  C  A  A  B  D  D
N00000014  B  B  D  D  C  B     D  C  C  ...  C     D  A  C  A  A     D  D
N00000015  A  C  C  D  C  B     A  C  C  ...  C  B  D  A  C  A  B     D  D
N00000016  B  A  C  D     B  D  A  C  C  ...  C  B  D  A  C  A  A  B  D  D
N00000017  B  A  D  D  C  B  C  A  D  C  ...  C  B  D  D  B     A  B  D  D
N00000018  B  A  D  A  C  B  D  A  C  C  ...     B  D  A  B  A  A  B     D
N00000019  B  A  D  D  C  B  D  C  C  C  ...  C  B  D  A     A  A  B  D  D
N00000020  B     D  D  C  B  D  A  C  B  ...  D  B  D  B  C  A  A  B  D  D

[20 rows x 25 columns]

In [25]:
all_student.eq(answer_key, axis = 1)

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
N00000021,False,False,False,True,False,True,False,True,False,False,...,False,False,False,True,False,False,False,False,False,False
N00000022,False,False,False,False,False,False,False,True,False,False,...,False,False,True,True,False,False,False,False,False,False
N00000024,False,True,False,True,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
N00000026,False,True,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
N00000028,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
N00000029,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
N00000030,False,False,False,True,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
N00000031,False,False,False,True,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
N00000032,False,False,False,True,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
N00000033,False,False,False,True,False,False,False,False,False,False,...,False,True,False,True,False,False,False,False,False,False
N00000034,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
N00000036,False,False,False,True,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
N00000037,False,False,False,True,False,False,False,False,False,False,...,True,False,False,True,False,False,False,False,False,False
N00000038,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
N00000039,False,False,False,True,False,False,False,False,False,False,...,False,True,False,True,True,False,False,False,False,False
N00000040,False,False,False,True,False,False,False,True,False,False,...,False,False,False,True,False,False,False,False,False,False
N00000041,False,False,False,True,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
N00000042,False,False,False,True,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
N00000043,False,False,False,True,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
N00000044,False,False,False,True,False,False,False,False,False,False,...,True,False,False,True,False,True,False,False,False,False
N00000045,False,False,False,True,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False

In [28]:
type(score)

pandas.core.series.Series

In [26]:
all_student[all_student.eq(answer_key)]

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
N00000021,NaN,NaN,NaN,D,NaN,C,NaN,D,NaN,NaN,...,NaN,NaN,NaN,A,NaN,NaN,NaN,NaN,NaN,NaN
N00000022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,NaN,NaN,...,NaN,NaN,A,A,NaN,NaN,NaN,NaN,NaN,NaN
N00000024,NaN,C,NaN,D,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,A,NaN,NaN,NaN,NaN,NaN,NaN
N00000026,NaN,C,NaN,D,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
N00000028,NaN,NaN,NaN,D,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
N00000029,NaN,NaN,NaN,D,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
N00000030,NaN,NaN,NaN,D,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,A,NaN,NaN,NaN,NaN,NaN,NaN
N00000031,NaN,NaN,NaN,D,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,A,NaN,NaN,NaN,NaN,NaN,NaN
N00000032,NaN,NaN,NaN,D,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,A,NaN,NaN,NaN,NaN,NaN,NaN
N00000033,NaN,NaN,NaN,D,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,C,NaN,A,NaN,NaN,NaN,NaN,NaN,NaN
N00000034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
N00000036,NaN,NaN,NaN,D,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,A,NaN,NaN,NaN,NaN,NaN,NaN
N00000037,NaN,NaN,NaN,D,NaN,NaN,NaN,NaN,NaN,NaN,...,A,NaN,NaN,A,NaN,NaN,NaN,NaN,NaN,NaN
N00000038,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,D,NaN,NaN,NaN
N00000039,NaN,NaN,NaN,D,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,C,NaN,A,B,NaN,NaN,NaN,NaN,NaN
N00000040,NaN,NaN,NaN,D,NaN,NaN,NaN,D,NaN,NaN,...,NaN,NaN,NaN,A,NaN,NaN,NaN,NaN,NaN,NaN
N00000041,NaN,NaN,NaN,D,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,A,NaN,NaN,NaN,NaN,NaN,NaN
N00000042,NaN,NaN,NaN,D,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,A,NaN,NaN,NaN,NaN,NaN,NaN
N00000043,NaN,NaN,NaN,D,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,A,NaN,NaN,NaN,NaN,NaN,NaN
N00000044,NaN,NaN,NaN,D,NaN,NaN,NaN,NaN,NaN,NaN,...,A,NaN,NaN,A,NaN,D,NaN,NaN,NaN,NaN
N00000045,NaN,NaN,NaN,D,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN